### PR TITLE
Refactor clusterer choice

### PR DESCRIPTION
**Pull request by wwood**
Thoughts about the last commit @AroneyS ? I actually didn't think hard about this very much - copilot did most of the coding, but seems pretty straightforward.

The tests don't pass, I guess because of the 100 issue you mentioned. If you like this can you take it to completion please?

Thanks, ben

### CODE REVIEW

**Comment by AroneyS** [comment]
Well that is much easier than I was thinking. I couldn't work out how to use the internal clusterer within the enum. But accessing the methods directly makes sense. I'll see if I can fix the tests.

**Comment by AroneyS** [comment]
Is there a reason that parse_percentage returns a decimal? https://github.com/wwood/galah/blob/31a6edd14e3417ba4cb69744fb8402f1e414a23a/src/cluster_argument_parsing.rs#L1015
Seems odd to do that and then multiply by 100 when we need it...

**Comment by wwood** [comment]
I guess it's just that the decimal is a bit human. Also worried a change might break coverm etc

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________

**Comment by wwood** [comment]
superseded by https://github.com/wwood/galah/pull/33

**Pull request closed without merging**
