### PR TITLE
Skani preclusterer speed-up

### PR DESCRIPTION
**Pull request by AroneyS**
- [x] Properly screen before ANI clustering
- [x] Use precluster clusters if preclusterer == clusterer
  - [x] Skip clustering
  - [x] Set precluster ANI to cluster ANI
- [x] Manually test

### CODE REVIEW

**Comment by wwood** [comment]
Hey so this is good to go you reckon?

**Comment by AroneyS** [comment]
Preclustering the 36k genomes from before takes 15mins now (down from 6 hours). Yay!

But, currently skani+skani will run skani twice. Just need to add a check for when preclusterer=clusterer.
Also, we have the triangle implementation in skani preclusterer, so it gets the more permissive ANI cutoff. How should we handle that? If preclusterer=clusterer then pass final ANI cutoff to preclusterer and skip clusterer?

**Comment by wwood** [comment]
Great. That sounds reasonable.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________

**Review by wwood — APPROVED** [review]

**Comment by wwood** [comment]
ok if you are?

**Comment by AroneyS** [comment]
[like]  Sam Aroney reacted to your message:
________________________________

**Comment by AroneyS** [comment]
[0]     Sam Aroney reacted to your message:
________________________________

**Pull request merged**
